version: '3'

services: 
  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "5436:5436"
    environment: 
      POSTGRES_PASSWORD: ${DB_PSW}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes: 
      - ./postgres:/var/lib/postgresql/data